// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mirabuiltin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from mirabuiltin.proto</summary>
public static partial class MirabuiltinReflection {

  #region Descriptor
  /// <summary>File descriptor for mirabuiltin.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MirabuiltinReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFtaXJhYnVpbHRpbi5wcm90byJLCglQYk1lc3NhZ2USIgoIY2F0ZWdvcnkY",
          "ASABKA4yEC5NZXNzYWdlQ2F0ZWdvcnkSDAoEdHlwZRgCIAEoDRIMCgRkYXRh",
          "GAMgASgMKlcKD01lc3NhZ2VDYXRlZ29yeRIICgROT05FEAASCgoGU1lTVEVN",
          "EAESBwoDTE9HEAISCQoFREVCVUcQAxIICgRGSUxFEAQSBwoDQ01EEAUSBwoD",
          "TUFYEAZiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MessageCategory), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PbMessage), global::PbMessage.Parser, new[]{ "Category", "Type", "Data" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
/// This holds each kind of message request that will be going through mira
/// </summary>
public enum MessageCategory {
  /// <summary>
  /// This is used for no message category
  /// </summary>
  [pbr::OriginalName("NONE")] None = 0,
  /// <summary>
  /// System messages
  /// </summary>
  [pbr::OriginalName("SYSTEM")] System = 1,
  /// <summary>
  /// Logging messages
  /// </summary>
  [pbr::OriginalName("LOG")] Log = 2,
  /// <summary>
  /// Debugger messages
  /// </summary>
  [pbr::OriginalName("DEBUG")] Debug = 3,
  /// <summary>
  /// File manager messages
  /// </summary>
  [pbr::OriginalName("FILE")] File = 4,
  /// <summary>
  /// Generic command messages
  /// </summary>
  [pbr::OriginalName("CMD")] Cmd = 5,
  /// <summary>
  /// THIS MUST ALWAYS BE THE LAST
  /// </summary>
  [pbr::OriginalName("MAX")] Max = 6,
}

#endregion

#region Messages
public sealed partial class PbMessage : pb::IMessage<PbMessage> {
  private static readonly pb::MessageParser<PbMessage> _parser = new pb::MessageParser<PbMessage>(() => new PbMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PbMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MirabuiltinReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PbMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PbMessage(PbMessage other) : this() {
    category_ = other.category_;
    type_ = other.type_;
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PbMessage Clone() {
    return new PbMessage(this);
  }

  /// <summary>Field number for the "category" field.</summary>
  public const int CategoryFieldNumber = 1;
  private global::MessageCategory category_ = 0;
  /// <summary>
  /// The category of each message
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::MessageCategory Category {
    get { return category_; }
    set {
      category_ = value;
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 2;
  private uint type_;
  /// <summary>
  /// The message type (CRC32(&lt;Message Type Name>))
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 3;
  private pb::ByteString data_ = pb::ByteString.Empty;
  /// <summary>
  /// The self contained protobuf message
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Data {
    get { return data_; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PbMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PbMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Category != other.Category) return false;
    if (Type != other.Type) return false;
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Category != 0) hash ^= Category.GetHashCode();
    if (Type != 0) hash ^= Type.GetHashCode();
    if (Data.Length != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Category != 0) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Category);
    }
    if (Type != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Type);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Category != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
    }
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
    }
    if (Data.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PbMessage other) {
    if (other == null) {
      return;
    }
    if (other.Category != 0) {
      Category = other.Category;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.Data.Length != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Category = (global::MessageCategory) input.ReadEnum();
          break;
        }
        case 16: {
          Type = input.ReadUInt32();
          break;
        }
        case 26: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
