/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messagetest.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messagetest.pb-c.h"
void   my_header__init
                     (MyHeader         *message)
{
  static MyHeader init_value = MY_HEADER__INIT;
  *message = init_value;
}
size_t my_header__get_packed_size
                     (const MyHeader *message)
{
  assert(message->base.descriptor == &my_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t my_header__pack
                     (const MyHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &my_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t my_header__pack_to_buffer
                     (const MyHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &my_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MyHeader *
       my_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MyHeader *)
     protobuf_c_message_unpack (&my_header__descriptor,
                                allocator, len, data);
}
void   my_header__free_unpacked
                     (MyHeader *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &my_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   my_other_message__init
                     (MyOtherMessage         *message)
{
  static MyOtherMessage init_value = MY_OTHER_MESSAGE__INIT;
  *message = init_value;
}
size_t my_other_message__get_packed_size
                     (const MyOtherMessage *message)
{
  assert(message->base.descriptor == &my_other_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t my_other_message__pack
                     (const MyOtherMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &my_other_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t my_other_message__pack_to_buffer
                     (const MyOtherMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &my_other_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MyOtherMessage *
       my_other_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MyOtherMessage *)
     protobuf_c_message_unpack (&my_other_message__descriptor,
                                allocator, len, data);
}
void   my_other_message__free_unpacked
                     (MyOtherMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &my_other_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor my_header__field_descriptors[3] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MyHeader, category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MyHeader, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MyHeader, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned my_header__field_indices_by_name[] = {
  0,   /* field[0] = category */
  2,   /* field[2] = error */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange my_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor my_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MyHeader",
  "MyHeader",
  "MyHeader",
  "",
  sizeof(MyHeader),
  3,
  my_header__field_descriptors,
  my_header__field_indices_by_name,
  1,  my_header__number_ranges,
  (ProtobufCMessageInit) my_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor my_other_message__field_descriptors[2] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MyOtherMessage, header),
    &my_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yamsayin",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MyOtherMessage, yamsayin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned my_other_message__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = yamsayin */
};
static const ProtobufCIntRange my_other_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor my_other_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MyOtherMessage",
  "MyOtherMessage",
  "MyOtherMessage",
  "",
  sizeof(MyOtherMessage),
  2,
  my_other_message__field_descriptors,
  my_other_message__field_indices_by_name,
  1,  my_other_message__number_ranges,
  (ProtobufCMessageInit) my_other_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
