/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mirabuiltin.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mirabuiltin.pb-c.h"
void   pb_message__init
                     (PbMessage         *message)
{
  static PbMessage init_value = PB_MESSAGE__INIT;
  *message = init_value;
}
size_t pb_message__get_packed_size
                     (const PbMessage *message)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb_message__pack
                     (const PbMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb_message__pack_to_buffer
                     (const PbMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbMessage *
       pb_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbMessage *)
     protobuf_c_message_unpack (&pb_message__descriptor,
                                allocator, len, data);
}
void   pb_message__free_unpacked
                     (PbMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb_message__field_descriptors[4] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PbMessage, category),
    &message_category__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbMessage, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PbMessage, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PbMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb_message__field_indices_by_name[] = {
  0,   /* field[0] = category */
  3,   /* field[3] = data */
  2,   /* field[2] = error */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange pb_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pb_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PbMessage",
  "PbMessage",
  "PbMessage",
  "",
  sizeof(PbMessage),
  4,
  pb_message__field_descriptors,
  pb_message__field_indices_by_name,
  1,  pb_message__number_ranges,
  (ProtobufCMessageInit) pb_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_category__enum_values_by_number[7] =
{
  { "NONE", "MESSAGE_CATEGORY__NONE", 0 },
  { "SYSTEM", "MESSAGE_CATEGORY__SYSTEM", 1 },
  { "LOG", "MESSAGE_CATEGORY__LOG", 2 },
  { "DEBUG", "MESSAGE_CATEGORY__DEBUG", 3 },
  { "FILE", "MESSAGE_CATEGORY__FILE", 4 },
  { "CMD", "MESSAGE_CATEGORY__CMD", 5 },
  { "MAX", "MESSAGE_CATEGORY__MAX", 6 },
};
static const ProtobufCIntRange message_category__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex message_category__enum_values_by_name[7] =
{
  { "CMD", 5 },
  { "DEBUG", 3 },
  { "FILE", 4 },
  { "LOG", 2 },
  { "MAX", 6 },
  { "NONE", 0 },
  { "SYSTEM", 1 },
};
const ProtobufCEnumDescriptor message_category__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageCategory",
  "MessageCategory",
  "MessageCategory",
  "",
  7,
  message_category__enum_values_by_number,
  7,
  message_category__enum_values_by_name,
  1,
  message_category__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
