#ifndef MIRABUILTIN.IDL_VERIFIER_H
#define MIRABUILTIN.IDL_VERIFIER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef MIRABUILTIN.IDL_READER_H
#include "MiraBuiltin.idl_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int MiraBuiltin_FbMessage_verify_table(flatcc_table_verifier_descriptor_t *td);

static int MiraBuiltin_FbMessage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* category */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* type */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 2, 0, 1, 1, INT64_C(4294967295)) /* payload */)) return ret;
    return flatcc_verify_ok;
}

static inline int MiraBuiltin_FbMessage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MiraBuiltin_FbMessage_identifier, &MiraBuiltin_FbMessage_verify_table);
}

static inline int MiraBuiltin_FbMessage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, MiraBuiltin_FbMessage_type_identifier, &MiraBuiltin_FbMessage_verify_table);
}

static inline int MiraBuiltin_FbMessage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &MiraBuiltin_FbMessage_verify_table);
}

static inline int MiraBuiltin_FbMessage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &MiraBuiltin_FbMessage_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* MIRABUILTIN.IDL_VERIFIER_H */
