#ifndef MIRABUILTIN.IDL_READER_H
#define MIRABUILTIN.IDL_READER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct MiraBuiltin_FbMessage_table *MiraBuiltin_FbMessage_table_t;
typedef const flatbuffers_uoffset_t *MiraBuiltin_FbMessage_vec_t;
typedef flatbuffers_uoffset_t *MiraBuiltin_FbMessage_mutable_vec_t;
#ifndef MiraBuiltin_FbMessage_identifier
#define MiraBuiltin_FbMessage_identifier flatbuffers_identifier
#endif
#define MiraBuiltin_FbMessage_type_hash ((flatbuffers_thash_t)0xa023b080)
#define MiraBuiltin_FbMessage_type_identifier "\x80\xb0\x23\xa0"

typedef int8_t MiraBuiltin_MessageCategory_enum_t;
__flatbuffers_define_integer_type(MiraBuiltin_MessageCategory, MiraBuiltin_MessageCategory_enum_t, 8)
#define MiraBuiltin_MessageCategory_NONE ((MiraBuiltin_MessageCategory_enum_t)INT8_C(0))
#define MiraBuiltin_MessageCategory_SYSTEM ((MiraBuiltin_MessageCategory_enum_t)INT8_C(1))
#define MiraBuiltin_MessageCategory_LOG ((MiraBuiltin_MessageCategory_enum_t)INT8_C(2))
#define MiraBuiltin_MessageCategory_DEBUG ((MiraBuiltin_MessageCategory_enum_t)INT8_C(3))
#define MiraBuiltin_MessageCategory_FILE ((MiraBuiltin_MessageCategory_enum_t)INT8_C(4))
#define MiraBuiltin_MessageCategory_CMD ((MiraBuiltin_MessageCategory_enum_t)INT8_C(5))
#define MiraBuiltin_MessageCategory_MAX ((MiraBuiltin_MessageCategory_enum_t)INT8_C(6))

static inline const char *MiraBuiltin_MessageCategory_name(MiraBuiltin_MessageCategory_enum_t value)
{
    switch (value) {
    case MiraBuiltin_MessageCategory_NONE: return "NONE";
    case MiraBuiltin_MessageCategory_SYSTEM: return "SYSTEM";
    case MiraBuiltin_MessageCategory_LOG: return "LOG";
    case MiraBuiltin_MessageCategory_DEBUG: return "DEBUG";
    case MiraBuiltin_MessageCategory_FILE: return "FILE";
    case MiraBuiltin_MessageCategory_CMD: return "CMD";
    case MiraBuiltin_MessageCategory_MAX: return "MAX";
    default: return "";
    }
}

static inline int MiraBuiltin_MessageCategory_is_known_value(MiraBuiltin_MessageCategory_enum_t value)
{
    switch (value) {
    case MiraBuiltin_MessageCategory_NONE: return 1;
    case MiraBuiltin_MessageCategory_SYSTEM: return 1;
    case MiraBuiltin_MessageCategory_LOG: return 1;
    case MiraBuiltin_MessageCategory_DEBUG: return 1;
    case MiraBuiltin_MessageCategory_FILE: return 1;
    case MiraBuiltin_MessageCategory_CMD: return 1;
    case MiraBuiltin_MessageCategory_MAX: return 1;
    default: return 0;
    }
}

typedef int8_t MiraBuiltin_Errors_enum_t;
__flatbuffers_define_integer_type(MiraBuiltin_Errors, MiraBuiltin_Errors_enum_t, 8)
#define MiraBuiltin_Errors_EOK ((MiraBuiltin_Errors_enum_t)INT8_C(0))
#define MiraBuiltin_Errors_EPERM ((MiraBuiltin_Errors_enum_t)INT8_C(1))
#define MiraBuiltin_Errors_ENOENT ((MiraBuiltin_Errors_enum_t)INT8_C(2))
#define MiraBuiltin_Errors_ESRCH ((MiraBuiltin_Errors_enum_t)INT8_C(3))
#define MiraBuiltin_Errors_EINTR ((MiraBuiltin_Errors_enum_t)INT8_C(4))
#define MiraBuiltin_Errors_EIO ((MiraBuiltin_Errors_enum_t)INT8_C(5))
#define MiraBuiltin_Errors_ENXIO ((MiraBuiltin_Errors_enum_t)INT8_C(6))
#define MiraBuiltin_Errors_E2BIG ((MiraBuiltin_Errors_enum_t)INT8_C(7))
#define MiraBuiltin_Errors_ENOEXEC ((MiraBuiltin_Errors_enum_t)INT8_C(8))
#define MiraBuiltin_Errors_EBADF ((MiraBuiltin_Errors_enum_t)INT8_C(9))
#define MiraBuiltin_Errors_ECHILD ((MiraBuiltin_Errors_enum_t)INT8_C(10))
#define MiraBuiltin_Errors_EDEADLK ((MiraBuiltin_Errors_enum_t)INT8_C(11))
#define MiraBuiltin_Errors_ENOMEM ((MiraBuiltin_Errors_enum_t)INT8_C(12))
#define MiraBuiltin_Errors_EACCES ((MiraBuiltin_Errors_enum_t)INT8_C(13))
#define MiraBuiltin_Errors_EFAULT ((MiraBuiltin_Errors_enum_t)INT8_C(14))
#define MiraBuiltin_Errors_ENOTBLK ((MiraBuiltin_Errors_enum_t)INT8_C(15))
#define MiraBuiltin_Errors_EBUSY ((MiraBuiltin_Errors_enum_t)INT8_C(16))
#define MiraBuiltin_Errors_EEXIST ((MiraBuiltin_Errors_enum_t)INT8_C(17))
#define MiraBuiltin_Errors_EXDEV ((MiraBuiltin_Errors_enum_t)INT8_C(18))
#define MiraBuiltin_Errors_ENODEV ((MiraBuiltin_Errors_enum_t)INT8_C(19))
#define MiraBuiltin_Errors_ENOTDIR ((MiraBuiltin_Errors_enum_t)INT8_C(20))
#define MiraBuiltin_Errors_EISDIR ((MiraBuiltin_Errors_enum_t)INT8_C(21))
#define MiraBuiltin_Errors_EINVAL ((MiraBuiltin_Errors_enum_t)INT8_C(22))
#define MiraBuiltin_Errors_ENFILE ((MiraBuiltin_Errors_enum_t)INT8_C(23))
#define MiraBuiltin_Errors_EMFILE ((MiraBuiltin_Errors_enum_t)INT8_C(24))
#define MiraBuiltin_Errors_ENOTTY ((MiraBuiltin_Errors_enum_t)INT8_C(25))
#define MiraBuiltin_Errors_ETXTBSY ((MiraBuiltin_Errors_enum_t)INT8_C(26))
#define MiraBuiltin_Errors_EFBIG ((MiraBuiltin_Errors_enum_t)INT8_C(27))
#define MiraBuiltin_Errors_ENOSPC ((MiraBuiltin_Errors_enum_t)INT8_C(28))
#define MiraBuiltin_Errors_ESPIPE ((MiraBuiltin_Errors_enum_t)INT8_C(29))
#define MiraBuiltin_Errors_EROFS ((MiraBuiltin_Errors_enum_t)INT8_C(30))
#define MiraBuiltin_Errors_EMLINK ((MiraBuiltin_Errors_enum_t)INT8_C(31))
#define MiraBuiltin_Errors_EPIPE ((MiraBuiltin_Errors_enum_t)INT8_C(32))
#define MiraBuiltin_Errors_EDOM ((MiraBuiltin_Errors_enum_t)INT8_C(33))
#define MiraBuiltin_Errors_ERANGE ((MiraBuiltin_Errors_enum_t)INT8_C(34))
#define MiraBuiltin_Errors_EAGAIN ((MiraBuiltin_Errors_enum_t)INT8_C(35))
#define MiraBuiltin_Errors_EINPROGRESS ((MiraBuiltin_Errors_enum_t)INT8_C(36))
#define MiraBuiltin_Errors_EALREADY ((MiraBuiltin_Errors_enum_t)INT8_C(37))
#define MiraBuiltin_Errors_ENOTSOCK ((MiraBuiltin_Errors_enum_t)INT8_C(38))
#define MiraBuiltin_Errors_EDESTADDRREQ ((MiraBuiltin_Errors_enum_t)INT8_C(39))
#define MiraBuiltin_Errors_EMSGSIZE ((MiraBuiltin_Errors_enum_t)INT8_C(40))
#define MiraBuiltin_Errors_EPROTOTYPE ((MiraBuiltin_Errors_enum_t)INT8_C(41))
#define MiraBuiltin_Errors_ENOPROTOOPT ((MiraBuiltin_Errors_enum_t)INT8_C(42))
#define MiraBuiltin_Errors_EPROTONOSUPPORT ((MiraBuiltin_Errors_enum_t)INT8_C(43))
#define MiraBuiltin_Errors_ESOCKTNOSUPPORT ((MiraBuiltin_Errors_enum_t)INT8_C(44))
#define MiraBuiltin_Errors_EOPNOTSUPP ((MiraBuiltin_Errors_enum_t)INT8_C(45))
#define MiraBuiltin_Errors_EPFNOSUPPORT ((MiraBuiltin_Errors_enum_t)INT8_C(46))
#define MiraBuiltin_Errors_EAFNOSUPPORT ((MiraBuiltin_Errors_enum_t)INT8_C(47))
#define MiraBuiltin_Errors_EADDRINUSE ((MiraBuiltin_Errors_enum_t)INT8_C(48))
#define MiraBuiltin_Errors_EADDRNOTAVAIL ((MiraBuiltin_Errors_enum_t)INT8_C(49))
#define MiraBuiltin_Errors_ENETDOWN ((MiraBuiltin_Errors_enum_t)INT8_C(50))
#define MiraBuiltin_Errors_ENETUNREACH ((MiraBuiltin_Errors_enum_t)INT8_C(51))
#define MiraBuiltin_Errors_ENETRESET ((MiraBuiltin_Errors_enum_t)INT8_C(52))
#define MiraBuiltin_Errors_ECONNABORTED ((MiraBuiltin_Errors_enum_t)INT8_C(53))
#define MiraBuiltin_Errors_ECONNRESET ((MiraBuiltin_Errors_enum_t)INT8_C(54))
#define MiraBuiltin_Errors_ENOBUFS ((MiraBuiltin_Errors_enum_t)INT8_C(55))
#define MiraBuiltin_Errors_EISCONN ((MiraBuiltin_Errors_enum_t)INT8_C(56))
#define MiraBuiltin_Errors_ENOTCONN ((MiraBuiltin_Errors_enum_t)INT8_C(57))
#define MiraBuiltin_Errors_ESHUTDOWN ((MiraBuiltin_Errors_enum_t)INT8_C(58))
#define MiraBuiltin_Errors_ETOOMANYREFS ((MiraBuiltin_Errors_enum_t)INT8_C(59))
#define MiraBuiltin_Errors_ETIMEDOUT ((MiraBuiltin_Errors_enum_t)INT8_C(60))
#define MiraBuiltin_Errors_ECONNREFUSED ((MiraBuiltin_Errors_enum_t)INT8_C(61))
#define MiraBuiltin_Errors_ELOOP ((MiraBuiltin_Errors_enum_t)INT8_C(62))
#define MiraBuiltin_Errors_ENAMETOOLONG ((MiraBuiltin_Errors_enum_t)INT8_C(63))
#define MiraBuiltin_Errors_EHOSTDOWN ((MiraBuiltin_Errors_enum_t)INT8_C(64))
#define MiraBuiltin_Errors_EHOSTUNREACH ((MiraBuiltin_Errors_enum_t)INT8_C(65))
#define MiraBuiltin_Errors_ENOTEMPTY ((MiraBuiltin_Errors_enum_t)INT8_C(66))
#define MiraBuiltin_Errors_EPROCLIM ((MiraBuiltin_Errors_enum_t)INT8_C(67))
#define MiraBuiltin_Errors_EUSERS ((MiraBuiltin_Errors_enum_t)INT8_C(68))
#define MiraBuiltin_Errors_EDQUOT ((MiraBuiltin_Errors_enum_t)INT8_C(69))
#define MiraBuiltin_Errors_ESTALE ((MiraBuiltin_Errors_enum_t)INT8_C(70))
#define MiraBuiltin_Errors_EREMOTE ((MiraBuiltin_Errors_enum_t)INT8_C(71))
#define MiraBuiltin_Errors_EBADRPC ((MiraBuiltin_Errors_enum_t)INT8_C(72))
#define MiraBuiltin_Errors_ERPCMISMATCH ((MiraBuiltin_Errors_enum_t)INT8_C(73))
#define MiraBuiltin_Errors_EPROGUNAVAIL ((MiraBuiltin_Errors_enum_t)INT8_C(74))
#define MiraBuiltin_Errors_EPROGMISMATCH ((MiraBuiltin_Errors_enum_t)INT8_C(75))
#define MiraBuiltin_Errors_EPROCUNAVAIL ((MiraBuiltin_Errors_enum_t)INT8_C(76))
#define MiraBuiltin_Errors_ENOLCK ((MiraBuiltin_Errors_enum_t)INT8_C(77))
#define MiraBuiltin_Errors_ENOSYS ((MiraBuiltin_Errors_enum_t)INT8_C(78))
#define MiraBuiltin_Errors_EFTYPE ((MiraBuiltin_Errors_enum_t)INT8_C(79))
#define MiraBuiltin_Errors_EAUTH ((MiraBuiltin_Errors_enum_t)INT8_C(80))
#define MiraBuiltin_Errors_ENEEDAUTH ((MiraBuiltin_Errors_enum_t)INT8_C(81))
#define MiraBuiltin_Errors_EIDRM ((MiraBuiltin_Errors_enum_t)INT8_C(82))
#define MiraBuiltin_Errors_ENOMSG ((MiraBuiltin_Errors_enum_t)INT8_C(83))
#define MiraBuiltin_Errors_EOVERFLOW ((MiraBuiltin_Errors_enum_t)INT8_C(84))
#define MiraBuiltin_Errors_ECANCELED ((MiraBuiltin_Errors_enum_t)INT8_C(85))
#define MiraBuiltin_Errors_EILSEQ ((MiraBuiltin_Errors_enum_t)INT8_C(86))
#define MiraBuiltin_Errors_ENOATTR ((MiraBuiltin_Errors_enum_t)INT8_C(87))
#define MiraBuiltin_Errors_EDOOFUS ((MiraBuiltin_Errors_enum_t)INT8_C(88))
#define MiraBuiltin_Errors_EBADMSG ((MiraBuiltin_Errors_enum_t)INT8_C(89))
#define MiraBuiltin_Errors_EMULTIHOP ((MiraBuiltin_Errors_enum_t)INT8_C(90))
#define MiraBuiltin_Errors_ENOLINK ((MiraBuiltin_Errors_enum_t)INT8_C(91))
#define MiraBuiltin_Errors_EPROTO ((MiraBuiltin_Errors_enum_t)INT8_C(92))
#define MiraBuiltin_Errors_ENOTCAPABLE ((MiraBuiltin_Errors_enum_t)INT8_C(93))
#define MiraBuiltin_Errors_ELAST ((MiraBuiltin_Errors_enum_t)INT8_C(94))

static inline const char *MiraBuiltin_Errors_name(MiraBuiltin_Errors_enum_t value)
{
    switch (value) {
    case MiraBuiltin_Errors_EOK: return "EOK";
    case MiraBuiltin_Errors_EPERM: return "EPERM";
    case MiraBuiltin_Errors_ENOENT: return "ENOENT";
    case MiraBuiltin_Errors_ESRCH: return "ESRCH";
    case MiraBuiltin_Errors_EINTR: return "EINTR";
    case MiraBuiltin_Errors_EIO: return "EIO";
    case MiraBuiltin_Errors_ENXIO: return "ENXIO";
    case MiraBuiltin_Errors_E2BIG: return "E2BIG";
    case MiraBuiltin_Errors_ENOEXEC: return "ENOEXEC";
    case MiraBuiltin_Errors_EBADF: return "EBADF";
    case MiraBuiltin_Errors_ECHILD: return "ECHILD";
    case MiraBuiltin_Errors_EDEADLK: return "EDEADLK";
    case MiraBuiltin_Errors_ENOMEM: return "ENOMEM";
    case MiraBuiltin_Errors_EACCES: return "EACCES";
    case MiraBuiltin_Errors_EFAULT: return "EFAULT";
    case MiraBuiltin_Errors_ENOTBLK: return "ENOTBLK";
    case MiraBuiltin_Errors_EBUSY: return "EBUSY";
    case MiraBuiltin_Errors_EEXIST: return "EEXIST";
    case MiraBuiltin_Errors_EXDEV: return "EXDEV";
    case MiraBuiltin_Errors_ENODEV: return "ENODEV";
    case MiraBuiltin_Errors_ENOTDIR: return "ENOTDIR";
    case MiraBuiltin_Errors_EISDIR: return "EISDIR";
    case MiraBuiltin_Errors_EINVAL: return "EINVAL";
    case MiraBuiltin_Errors_ENFILE: return "ENFILE";
    case MiraBuiltin_Errors_EMFILE: return "EMFILE";
    case MiraBuiltin_Errors_ENOTTY: return "ENOTTY";
    case MiraBuiltin_Errors_ETXTBSY: return "ETXTBSY";
    case MiraBuiltin_Errors_EFBIG: return "EFBIG";
    case MiraBuiltin_Errors_ENOSPC: return "ENOSPC";
    case MiraBuiltin_Errors_ESPIPE: return "ESPIPE";
    case MiraBuiltin_Errors_EROFS: return "EROFS";
    case MiraBuiltin_Errors_EMLINK: return "EMLINK";
    case MiraBuiltin_Errors_EPIPE: return "EPIPE";
    case MiraBuiltin_Errors_EDOM: return "EDOM";
    case MiraBuiltin_Errors_ERANGE: return "ERANGE";
    case MiraBuiltin_Errors_EAGAIN: return "EAGAIN";
    case MiraBuiltin_Errors_EINPROGRESS: return "EINPROGRESS";
    case MiraBuiltin_Errors_EALREADY: return "EALREADY";
    case MiraBuiltin_Errors_ENOTSOCK: return "ENOTSOCK";
    case MiraBuiltin_Errors_EDESTADDRREQ: return "EDESTADDRREQ";
    case MiraBuiltin_Errors_EMSGSIZE: return "EMSGSIZE";
    case MiraBuiltin_Errors_EPROTOTYPE: return "EPROTOTYPE";
    case MiraBuiltin_Errors_ENOPROTOOPT: return "ENOPROTOOPT";
    case MiraBuiltin_Errors_EPROTONOSUPPORT: return "EPROTONOSUPPORT";
    case MiraBuiltin_Errors_ESOCKTNOSUPPORT: return "ESOCKTNOSUPPORT";
    case MiraBuiltin_Errors_EOPNOTSUPP: return "EOPNOTSUPP";
    case MiraBuiltin_Errors_EPFNOSUPPORT: return "EPFNOSUPPORT";
    case MiraBuiltin_Errors_EAFNOSUPPORT: return "EAFNOSUPPORT";
    case MiraBuiltin_Errors_EADDRINUSE: return "EADDRINUSE";
    case MiraBuiltin_Errors_EADDRNOTAVAIL: return "EADDRNOTAVAIL";
    case MiraBuiltin_Errors_ENETDOWN: return "ENETDOWN";
    case MiraBuiltin_Errors_ENETUNREACH: return "ENETUNREACH";
    case MiraBuiltin_Errors_ENETRESET: return "ENETRESET";
    case MiraBuiltin_Errors_ECONNABORTED: return "ECONNABORTED";
    case MiraBuiltin_Errors_ECONNRESET: return "ECONNRESET";
    case MiraBuiltin_Errors_ENOBUFS: return "ENOBUFS";
    case MiraBuiltin_Errors_EISCONN: return "EISCONN";
    case MiraBuiltin_Errors_ENOTCONN: return "ENOTCONN";
    case MiraBuiltin_Errors_ESHUTDOWN: return "ESHUTDOWN";
    case MiraBuiltin_Errors_ETOOMANYREFS: return "ETOOMANYREFS";
    case MiraBuiltin_Errors_ETIMEDOUT: return "ETIMEDOUT";
    case MiraBuiltin_Errors_ECONNREFUSED: return "ECONNREFUSED";
    case MiraBuiltin_Errors_ELOOP: return "ELOOP";
    case MiraBuiltin_Errors_ENAMETOOLONG: return "ENAMETOOLONG";
    case MiraBuiltin_Errors_EHOSTDOWN: return "EHOSTDOWN";
    case MiraBuiltin_Errors_EHOSTUNREACH: return "EHOSTUNREACH";
    case MiraBuiltin_Errors_ENOTEMPTY: return "ENOTEMPTY";
    case MiraBuiltin_Errors_EPROCLIM: return "EPROCLIM";
    case MiraBuiltin_Errors_EUSERS: return "EUSERS";
    case MiraBuiltin_Errors_EDQUOT: return "EDQUOT";
    case MiraBuiltin_Errors_ESTALE: return "ESTALE";
    case MiraBuiltin_Errors_EREMOTE: return "EREMOTE";
    case MiraBuiltin_Errors_EBADRPC: return "EBADRPC";
    case MiraBuiltin_Errors_ERPCMISMATCH: return "ERPCMISMATCH";
    case MiraBuiltin_Errors_EPROGUNAVAIL: return "EPROGUNAVAIL";
    case MiraBuiltin_Errors_EPROGMISMATCH: return "EPROGMISMATCH";
    case MiraBuiltin_Errors_EPROCUNAVAIL: return "EPROCUNAVAIL";
    case MiraBuiltin_Errors_ENOLCK: return "ENOLCK";
    case MiraBuiltin_Errors_ENOSYS: return "ENOSYS";
    case MiraBuiltin_Errors_EFTYPE: return "EFTYPE";
    case MiraBuiltin_Errors_EAUTH: return "EAUTH";
    case MiraBuiltin_Errors_ENEEDAUTH: return "ENEEDAUTH";
    case MiraBuiltin_Errors_EIDRM: return "EIDRM";
    case MiraBuiltin_Errors_ENOMSG: return "ENOMSG";
    case MiraBuiltin_Errors_EOVERFLOW: return "EOVERFLOW";
    case MiraBuiltin_Errors_ECANCELED: return "ECANCELED";
    case MiraBuiltin_Errors_EILSEQ: return "EILSEQ";
    case MiraBuiltin_Errors_ENOATTR: return "ENOATTR";
    case MiraBuiltin_Errors_EDOOFUS: return "EDOOFUS";
    case MiraBuiltin_Errors_EBADMSG: return "EBADMSG";
    case MiraBuiltin_Errors_EMULTIHOP: return "EMULTIHOP";
    case MiraBuiltin_Errors_ENOLINK: return "ENOLINK";
    case MiraBuiltin_Errors_EPROTO: return "EPROTO";
    case MiraBuiltin_Errors_ENOTCAPABLE: return "ENOTCAPABLE";
    case MiraBuiltin_Errors_ELAST: return "ELAST";
    default: return "";
    }
}

static inline int MiraBuiltin_Errors_is_known_value(MiraBuiltin_Errors_enum_t value)
{
    switch (value) {
    case MiraBuiltin_Errors_EOK: return 1;
    case MiraBuiltin_Errors_EPERM: return 1;
    case MiraBuiltin_Errors_ENOENT: return 1;
    case MiraBuiltin_Errors_ESRCH: return 1;
    case MiraBuiltin_Errors_EINTR: return 1;
    case MiraBuiltin_Errors_EIO: return 1;
    case MiraBuiltin_Errors_ENXIO: return 1;
    case MiraBuiltin_Errors_E2BIG: return 1;
    case MiraBuiltin_Errors_ENOEXEC: return 1;
    case MiraBuiltin_Errors_EBADF: return 1;
    case MiraBuiltin_Errors_ECHILD: return 1;
    case MiraBuiltin_Errors_EDEADLK: return 1;
    case MiraBuiltin_Errors_ENOMEM: return 1;
    case MiraBuiltin_Errors_EACCES: return 1;
    case MiraBuiltin_Errors_EFAULT: return 1;
    case MiraBuiltin_Errors_ENOTBLK: return 1;
    case MiraBuiltin_Errors_EBUSY: return 1;
    case MiraBuiltin_Errors_EEXIST: return 1;
    case MiraBuiltin_Errors_EXDEV: return 1;
    case MiraBuiltin_Errors_ENODEV: return 1;
    case MiraBuiltin_Errors_ENOTDIR: return 1;
    case MiraBuiltin_Errors_EISDIR: return 1;
    case MiraBuiltin_Errors_EINVAL: return 1;
    case MiraBuiltin_Errors_ENFILE: return 1;
    case MiraBuiltin_Errors_EMFILE: return 1;
    case MiraBuiltin_Errors_ENOTTY: return 1;
    case MiraBuiltin_Errors_ETXTBSY: return 1;
    case MiraBuiltin_Errors_EFBIG: return 1;
    case MiraBuiltin_Errors_ENOSPC: return 1;
    case MiraBuiltin_Errors_ESPIPE: return 1;
    case MiraBuiltin_Errors_EROFS: return 1;
    case MiraBuiltin_Errors_EMLINK: return 1;
    case MiraBuiltin_Errors_EPIPE: return 1;
    case MiraBuiltin_Errors_EDOM: return 1;
    case MiraBuiltin_Errors_ERANGE: return 1;
    case MiraBuiltin_Errors_EAGAIN: return 1;
    case MiraBuiltin_Errors_EINPROGRESS: return 1;
    case MiraBuiltin_Errors_EALREADY: return 1;
    case MiraBuiltin_Errors_ENOTSOCK: return 1;
    case MiraBuiltin_Errors_EDESTADDRREQ: return 1;
    case MiraBuiltin_Errors_EMSGSIZE: return 1;
    case MiraBuiltin_Errors_EPROTOTYPE: return 1;
    case MiraBuiltin_Errors_ENOPROTOOPT: return 1;
    case MiraBuiltin_Errors_EPROTONOSUPPORT: return 1;
    case MiraBuiltin_Errors_ESOCKTNOSUPPORT: return 1;
    case MiraBuiltin_Errors_EOPNOTSUPP: return 1;
    case MiraBuiltin_Errors_EPFNOSUPPORT: return 1;
    case MiraBuiltin_Errors_EAFNOSUPPORT: return 1;
    case MiraBuiltin_Errors_EADDRINUSE: return 1;
    case MiraBuiltin_Errors_EADDRNOTAVAIL: return 1;
    case MiraBuiltin_Errors_ENETDOWN: return 1;
    case MiraBuiltin_Errors_ENETUNREACH: return 1;
    case MiraBuiltin_Errors_ENETRESET: return 1;
    case MiraBuiltin_Errors_ECONNABORTED: return 1;
    case MiraBuiltin_Errors_ECONNRESET: return 1;
    case MiraBuiltin_Errors_ENOBUFS: return 1;
    case MiraBuiltin_Errors_EISCONN: return 1;
    case MiraBuiltin_Errors_ENOTCONN: return 1;
    case MiraBuiltin_Errors_ESHUTDOWN: return 1;
    case MiraBuiltin_Errors_ETOOMANYREFS: return 1;
    case MiraBuiltin_Errors_ETIMEDOUT: return 1;
    case MiraBuiltin_Errors_ECONNREFUSED: return 1;
    case MiraBuiltin_Errors_ELOOP: return 1;
    case MiraBuiltin_Errors_ENAMETOOLONG: return 1;
    case MiraBuiltin_Errors_EHOSTDOWN: return 1;
    case MiraBuiltin_Errors_EHOSTUNREACH: return 1;
    case MiraBuiltin_Errors_ENOTEMPTY: return 1;
    case MiraBuiltin_Errors_EPROCLIM: return 1;
    case MiraBuiltin_Errors_EUSERS: return 1;
    case MiraBuiltin_Errors_EDQUOT: return 1;
    case MiraBuiltin_Errors_ESTALE: return 1;
    case MiraBuiltin_Errors_EREMOTE: return 1;
    case MiraBuiltin_Errors_EBADRPC: return 1;
    case MiraBuiltin_Errors_ERPCMISMATCH: return 1;
    case MiraBuiltin_Errors_EPROGUNAVAIL: return 1;
    case MiraBuiltin_Errors_EPROGMISMATCH: return 1;
    case MiraBuiltin_Errors_EPROCUNAVAIL: return 1;
    case MiraBuiltin_Errors_ENOLCK: return 1;
    case MiraBuiltin_Errors_ENOSYS: return 1;
    case MiraBuiltin_Errors_EFTYPE: return 1;
    case MiraBuiltin_Errors_EAUTH: return 1;
    case MiraBuiltin_Errors_ENEEDAUTH: return 1;
    case MiraBuiltin_Errors_EIDRM: return 1;
    case MiraBuiltin_Errors_ENOMSG: return 1;
    case MiraBuiltin_Errors_EOVERFLOW: return 1;
    case MiraBuiltin_Errors_ECANCELED: return 1;
    case MiraBuiltin_Errors_EILSEQ: return 1;
    case MiraBuiltin_Errors_ENOATTR: return 1;
    case MiraBuiltin_Errors_EDOOFUS: return 1;
    case MiraBuiltin_Errors_EBADMSG: return 1;
    case MiraBuiltin_Errors_EMULTIHOP: return 1;
    case MiraBuiltin_Errors_ENOLINK: return 1;
    case MiraBuiltin_Errors_EPROTO: return 1;
    case MiraBuiltin_Errors_ENOTCAPABLE: return 1;
    case MiraBuiltin_Errors_ELAST: return 1;
    default: return 0;
    }
}



struct MiraBuiltin_FbMessage_table { uint8_t unused__; };

static inline size_t MiraBuiltin_FbMessage_vec_len(MiraBuiltin_FbMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline MiraBuiltin_FbMessage_table_t MiraBuiltin_FbMessage_vec_at(MiraBuiltin_FbMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(MiraBuiltin_FbMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(MiraBuiltin_FbMessage)

__flatbuffers_define_scalar_field(0, MiraBuiltin_FbMessage, category, MiraBuiltin_MessageCategory, MiraBuiltin_MessageCategory_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(1, MiraBuiltin_FbMessage, type, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(2, MiraBuiltin_FbMessage, payload, flatbuffers_uint8_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* MIRABUILTIN.IDL_READER_H */
