#ifndef MIRABUILTIN.IDL_BUILDER_H
#define MIRABUILTIN.IDL_BUILDER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef MIRABUILTIN.IDL_READER_H
#include "MiraBuiltin.idl_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

#define __MiraBuiltin_MessageCategory_formal_args , MiraBuiltin_MessageCategory_enum_t v0
#define __MiraBuiltin_MessageCategory_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, MiraBuiltin_MessageCategory, MiraBuiltin_MessageCategory_enum_t)
#define __MiraBuiltin_Errors_formal_args , MiraBuiltin_Errors_enum_t v0
#define __MiraBuiltin_Errors_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, MiraBuiltin_Errors, MiraBuiltin_Errors_enum_t)

static const flatbuffers_voffset_t __MiraBuiltin_FbMessage_required[] = { 0 };
typedef flatbuffers_ref_t MiraBuiltin_FbMessage_ref_t;
static MiraBuiltin_FbMessage_ref_t MiraBuiltin_FbMessage_clone(flatbuffers_builder_t *B, MiraBuiltin_FbMessage_table_t t);
__flatbuffers_build_table(flatbuffers_, MiraBuiltin_FbMessage, 3)

#define __MiraBuiltin_FbMessage_formal_args , MiraBuiltin_MessageCategory_enum_t v0, uint32_t v1, flatbuffers_uint8_vec_ref_t v2
#define __MiraBuiltin_FbMessage_call_args , v0, v1, v2
static inline MiraBuiltin_FbMessage_ref_t MiraBuiltin_FbMessage_create(flatbuffers_builder_t *B __MiraBuiltin_FbMessage_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, MiraBuiltin_FbMessage, MiraBuiltin_FbMessage_identifier, MiraBuiltin_FbMessage_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, MiraBuiltin_FbMessage_category, MiraBuiltin_MessageCategory, MiraBuiltin_MessageCategory_enum_t, 1, 1, INT8_C(0), MiraBuiltin_FbMessage)
__flatbuffers_build_scalar_field(1, flatbuffers_, MiraBuiltin_FbMessage_type, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), MiraBuiltin_FbMessage)
__flatbuffers_build_vector_field(2, flatbuffers_, MiraBuiltin_FbMessage_payload, flatbuffers_uint8, uint8_t, MiraBuiltin_FbMessage)

static inline MiraBuiltin_FbMessage_ref_t MiraBuiltin_FbMessage_create(flatbuffers_builder_t *B __MiraBuiltin_FbMessage_formal_args)
{
    if (MiraBuiltin_FbMessage_start(B)
        || MiraBuiltin_FbMessage_type_add(B, v1)
        || MiraBuiltin_FbMessage_payload_add(B, v2)
        || MiraBuiltin_FbMessage_category_add(B, v0)) {
        return 0;
    }
    return MiraBuiltin_FbMessage_end(B);
}

static MiraBuiltin_FbMessage_ref_t MiraBuiltin_FbMessage_clone(flatbuffers_builder_t *B, MiraBuiltin_FbMessage_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (MiraBuiltin_FbMessage_start(B)
        || MiraBuiltin_FbMessage_type_pick(B, t)
        || MiraBuiltin_FbMessage_payload_pick(B, t)
        || MiraBuiltin_FbMessage_category_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, MiraBuiltin_FbMessage_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* MIRABUILTIN.IDL_BUILDER_H */
