/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mirabuiltin.proto */

#ifndef PROTOBUF_C_mirabuiltin_2eproto__INCLUDED
#define PROTOBUF_C_mirabuiltin_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PbMessage PbMessage;


/* --- enums --- */

/*
 * This holds each kind of message request that will be going through mira
 */
typedef enum _MessageCategory {
  /*
   * This is used for no message category
   */
  MESSAGE_CATEGORY__NONE = 0,
  /*
   * System messages
   */
  MESSAGE_CATEGORY__SYSTEM = 1,
  /*
   * Logging messages
   */
  MESSAGE_CATEGORY__LOG = 2,
  /*
   * Debugger messages
   */
  MESSAGE_CATEGORY__DEBUG = 3,
  /*
   * File manager messages
   */
  MESSAGE_CATEGORY__FILE = 4,
  /*
   * Generic command messages
   */
  MESSAGE_CATEGORY__CMD = 5,
  /*
   * THIS MUST ALWAYS BE THE LAST
   */
  MESSAGE_CATEGORY__MAX = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGE_CATEGORY)
} MessageCategory;

/* --- messages --- */

struct  _PbMessage
{
  ProtobufCMessage base;
  /*
   * The category of each message
   */
  MessageCategory category;
  /*
   * The message type (CRC32(<Message Type Name>))
   */
  uint32_t type;
  /*
   * The error code, 0 on success
   */
  int32_t error;
  /*
   * The self contained protobuf message
   */
  ProtobufCBinaryData data;
};
#define PB_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pb_message__descriptor) \
    , 0, 0, 0, {0,NULL} }


/* PbMessage methods */
void   pb_message__init
                     (PbMessage         *message);
size_t pb_message__get_packed_size
                     (const PbMessage   *message);
size_t pb_message__pack
                     (const PbMessage   *message,
                      uint8_t             *out);
size_t pb_message__pack_to_buffer
                     (const PbMessage   *message,
                      ProtobufCBuffer     *buffer);
PbMessage *
       pb_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pb_message__free_unpacked
                     (PbMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PbMessage_Closure)
                 (const PbMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    message_category__descriptor;
extern const ProtobufCMessageDescriptor pb_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mirabuiltin_2eproto__INCLUDED */
