/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mirabuiltin.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include <mirabuiltin.pb-c.h>

void   pb_message__init
                     (PbMessage         *message)
{
  static const PbMessage init_value = PB_MESSAGE__INIT;
  *message = init_value;
}
size_t pb_message__get_packed_size
                     (const PbMessage *message)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb_message__pack
                     (const PbMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb_message__pack_to_buffer
                     (const PbMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PbMessage *
       pb_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PbMessage *)
     protobuf_c_message_unpack (&pb_message__descriptor,
                                allocator, len, data);
}
void   pb_message__free_unpacked
                     (PbMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb_message__field_descriptors[3] =
{
  {
    "category",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PbMessage, category),
    &message_category__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PbMessage, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PbMessage, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb_message__field_indices_by_name[] = {
  0,   /* field[0] = category */
  2,   /* field[2] = payload */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange pb_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PbMessage",
  "PbMessage",
  "PbMessage",
  "",
  sizeof(PbMessage),
  3,
  pb_message__field_descriptors,
  pb_message__field_indices_by_name,
  1,  pb_message__number_ranges,
  (ProtobufCMessageInit) pb_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_category__enum_values_by_number[7] =
{
  { "NONE", "MESSAGE_CATEGORY__NONE", 0 },
  { "SYSTEM", "MESSAGE_CATEGORY__SYSTEM", 1 },
  { "LOG", "MESSAGE_CATEGORY__LOG", 2 },
  { "DEBUG", "MESSAGE_CATEGORY__DEBUG", 3 },
  { "FILE", "MESSAGE_CATEGORY__FILE", 4 },
  { "CMD", "MESSAGE_CATEGORY__CMD", 5 },
  { "MAX", "MESSAGE_CATEGORY__MAX", 6 },
};
static const ProtobufCIntRange message_category__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex message_category__enum_values_by_name[7] =
{
  { "CMD", 5 },
  { "DEBUG", 3 },
  { "FILE", 4 },
  { "LOG", 2 },
  { "MAX", 6 },
  { "NONE", 0 },
  { "SYSTEM", 1 },
};
const ProtobufCEnumDescriptor message_category__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageCategory",
  "MessageCategory",
  "MessageCategory",
  "",
  7,
  message_category__enum_values_by_number,
  7,
  message_category__enum_values_by_name,
  1,
  message_category__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue errors__enum_values_by_number[95] =
{
  { "EOK", "ERRORS__EOK", 0 },
  { "EPERM", "ERRORS__EPERM", 1 },
  { "ENOENT", "ERRORS__ENOENT", 2 },
  { "ESRCH", "ERRORS__ESRCH", 3 },
  { "EINTR", "ERRORS__EINTR", 4 },
  { "EIO", "ERRORS__EIO", 5 },
  { "ENXIO", "ERRORS__ENXIO", 6 },
  { "E2BIG", "ERRORS__E2BIG", 7 },
  { "ENOEXEC", "ERRORS__ENOEXEC", 8 },
  { "EBADF", "ERRORS__EBADF", 9 },
  { "ECHILD", "ERRORS__ECHILD", 10 },
  { "EDEADLK", "ERRORS__EDEADLK", 11 },
  { "ENOMEM", "ERRORS__ENOMEM", 12 },
  { "EACCES", "ERRORS__EACCES", 13 },
  { "EFAULT", "ERRORS__EFAULT", 14 },
  { "ENOTBLK", "ERRORS__ENOTBLK", 15 },
  { "EBUSY", "ERRORS__EBUSY", 16 },
  { "EEXIST", "ERRORS__EEXIST", 17 },
  { "EXDEV", "ERRORS__EXDEV", 18 },
  { "ENODEV", "ERRORS__ENODEV", 19 },
  { "ENOTDIR", "ERRORS__ENOTDIR", 20 },
  { "EISDIR", "ERRORS__EISDIR", 21 },
  { "EINVAL", "ERRORS__EINVAL", 22 },
  { "ENFILE", "ERRORS__ENFILE", 23 },
  { "EMFILE", "ERRORS__EMFILE", 24 },
  { "ENOTTY", "ERRORS__ENOTTY", 25 },
  { "ETXTBSY", "ERRORS__ETXTBSY", 26 },
  { "EFBIG", "ERRORS__EFBIG", 27 },
  { "ENOSPC", "ERRORS__ENOSPC", 28 },
  { "ESPIPE", "ERRORS__ESPIPE", 29 },
  { "EROFS", "ERRORS__EROFS", 30 },
  { "EMLINK", "ERRORS__EMLINK", 31 },
  { "EPIPE", "ERRORS__EPIPE", 32 },
  { "EDOM", "ERRORS__EDOM", 33 },
  { "ERANGE", "ERRORS__ERANGE", 34 },
  { "EAGAIN", "ERRORS__EAGAIN", 35 },
  { "EINPROGRESS", "ERRORS__EINPROGRESS", 36 },
  { "EALREADY", "ERRORS__EALREADY", 37 },
  { "ENOTSOCK", "ERRORS__ENOTSOCK", 38 },
  { "EDESTADDRREQ", "ERRORS__EDESTADDRREQ", 39 },
  { "EMSGSIZE", "ERRORS__EMSGSIZE", 40 },
  { "EPROTOTYPE", "ERRORS__EPROTOTYPE", 41 },
  { "ENOPROTOOPT", "ERRORS__ENOPROTOOPT", 42 },
  { "EPROTONOSUPPORT", "ERRORS__EPROTONOSUPPORT", 43 },
  { "ESOCKTNOSUPPORT", "ERRORS__ESOCKTNOSUPPORT", 44 },
  { "EOPNOTSUPP", "ERRORS__EOPNOTSUPP", 45 },
  { "EPFNOSUPPORT", "ERRORS__EPFNOSUPPORT", 46 },
  { "EAFNOSUPPORT", "ERRORS__EAFNOSUPPORT", 47 },
  { "EADDRINUSE", "ERRORS__EADDRINUSE", 48 },
  { "EADDRNOTAVAIL", "ERRORS__EADDRNOTAVAIL", 49 },
  { "ENETDOWN", "ERRORS__ENETDOWN", 50 },
  { "ENETUNREACH", "ERRORS__ENETUNREACH", 51 },
  { "ENETRESET", "ERRORS__ENETRESET", 52 },
  { "ECONNABORTED", "ERRORS__ECONNABORTED", 53 },
  { "ECONNRESET", "ERRORS__ECONNRESET", 54 },
  { "ENOBUFS", "ERRORS__ENOBUFS", 55 },
  { "EISCONN", "ERRORS__EISCONN", 56 },
  { "ENOTCONN", "ERRORS__ENOTCONN", 57 },
  { "ESHUTDOWN", "ERRORS__ESHUTDOWN", 58 },
  { "ETOOMANYREFS", "ERRORS__ETOOMANYREFS", 59 },
  { "ETIMEDOUT", "ERRORS__ETIMEDOUT", 60 },
  { "ECONNREFUSED", "ERRORS__ECONNREFUSED", 61 },
  { "ELOOP", "ERRORS__ELOOP", 62 },
  { "ENAMETOOLONG", "ERRORS__ENAMETOOLONG", 63 },
  { "EHOSTDOWN", "ERRORS__EHOSTDOWN", 64 },
  { "EHOSTUNREACH", "ERRORS__EHOSTUNREACH", 65 },
  { "ENOTEMPTY", "ERRORS__ENOTEMPTY", 66 },
  { "EPROCLIM", "ERRORS__EPROCLIM", 67 },
  { "EUSERS", "ERRORS__EUSERS", 68 },
  { "EDQUOT", "ERRORS__EDQUOT", 69 },
  { "ESTALE", "ERRORS__ESTALE", 70 },
  { "EREMOTE", "ERRORS__EREMOTE", 71 },
  { "EBADRPC", "ERRORS__EBADRPC", 72 },
  { "ERPCMISMATCH", "ERRORS__ERPCMISMATCH", 73 },
  { "EPROGUNAVAIL", "ERRORS__EPROGUNAVAIL", 74 },
  { "EPROGMISMATCH", "ERRORS__EPROGMISMATCH", 75 },
  { "EPROCUNAVAIL", "ERRORS__EPROCUNAVAIL", 76 },
  { "ENOLCK", "ERRORS__ENOLCK", 77 },
  { "ENOSYS", "ERRORS__ENOSYS", 78 },
  { "EFTYPE", "ERRORS__EFTYPE", 79 },
  { "EAUTH", "ERRORS__EAUTH", 80 },
  { "ENEEDAUTH", "ERRORS__ENEEDAUTH", 81 },
  { "EIDRM", "ERRORS__EIDRM", 82 },
  { "ENOMSG", "ERRORS__ENOMSG", 83 },
  { "EOVERFLOW", "ERRORS__EOVERFLOW", 84 },
  { "ECANCELED", "ERRORS__ECANCELED", 85 },
  { "EILSEQ", "ERRORS__EILSEQ", 86 },
  { "ENOATTR", "ERRORS__ENOATTR", 87 },
  { "EDOOFUS", "ERRORS__EDOOFUS", 88 },
  { "EBADMSG", "ERRORS__EBADMSG", 89 },
  { "EMULTIHOP", "ERRORS__EMULTIHOP", 90 },
  { "ENOLINK", "ERRORS__ENOLINK", 91 },
  { "EPROTO", "ERRORS__EPROTO", 92 },
  { "ENOTCAPABLE", "ERRORS__ENOTCAPABLE", 93 },
  { "ELAST", "ERRORS__ELAST", 94 },
};
static const ProtobufCIntRange errors__value_ranges[] = {
{0, 0},{0, 95}
};
static const ProtobufCEnumValueIndex errors__enum_values_by_name[95] =
{
  { "E2BIG", 7 },
  { "EACCES", 13 },
  { "EADDRINUSE", 48 },
  { "EADDRNOTAVAIL", 49 },
  { "EAFNOSUPPORT", 47 },
  { "EAGAIN", 35 },
  { "EALREADY", 37 },
  { "EAUTH", 80 },
  { "EBADF", 9 },
  { "EBADMSG", 89 },
  { "EBADRPC", 72 },
  { "EBUSY", 16 },
  { "ECANCELED", 85 },
  { "ECHILD", 10 },
  { "ECONNABORTED", 53 },
  { "ECONNREFUSED", 61 },
  { "ECONNRESET", 54 },
  { "EDEADLK", 11 },
  { "EDESTADDRREQ", 39 },
  { "EDOM", 33 },
  { "EDOOFUS", 88 },
  { "EDQUOT", 69 },
  { "EEXIST", 17 },
  { "EFAULT", 14 },
  { "EFBIG", 27 },
  { "EFTYPE", 79 },
  { "EHOSTDOWN", 64 },
  { "EHOSTUNREACH", 65 },
  { "EIDRM", 82 },
  { "EILSEQ", 86 },
  { "EINPROGRESS", 36 },
  { "EINTR", 4 },
  { "EINVAL", 22 },
  { "EIO", 5 },
  { "EISCONN", 56 },
  { "EISDIR", 21 },
  { "ELAST", 94 },
  { "ELOOP", 62 },
  { "EMFILE", 24 },
  { "EMLINK", 31 },
  { "EMSGSIZE", 40 },
  { "EMULTIHOP", 90 },
  { "ENAMETOOLONG", 63 },
  { "ENEEDAUTH", 81 },
  { "ENETDOWN", 50 },
  { "ENETRESET", 52 },
  { "ENETUNREACH", 51 },
  { "ENFILE", 23 },
  { "ENOATTR", 87 },
  { "ENOBUFS", 55 },
  { "ENODEV", 19 },
  { "ENOENT", 2 },
  { "ENOEXEC", 8 },
  { "ENOLCK", 77 },
  { "ENOLINK", 91 },
  { "ENOMEM", 12 },
  { "ENOMSG", 83 },
  { "ENOPROTOOPT", 42 },
  { "ENOSPC", 28 },
  { "ENOSYS", 78 },
  { "ENOTBLK", 15 },
  { "ENOTCAPABLE", 93 },
  { "ENOTCONN", 57 },
  { "ENOTDIR", 20 },
  { "ENOTEMPTY", 66 },
  { "ENOTSOCK", 38 },
  { "ENOTTY", 25 },
  { "ENXIO", 6 },
  { "EOK", 0 },
  { "EOPNOTSUPP", 45 },
  { "EOVERFLOW", 84 },
  { "EPERM", 1 },
  { "EPFNOSUPPORT", 46 },
  { "EPIPE", 32 },
  { "EPROCLIM", 67 },
  { "EPROCUNAVAIL", 76 },
  { "EPROGMISMATCH", 75 },
  { "EPROGUNAVAIL", 74 },
  { "EPROTO", 92 },
  { "EPROTONOSUPPORT", 43 },
  { "EPROTOTYPE", 41 },
  { "ERANGE", 34 },
  { "EREMOTE", 71 },
  { "EROFS", 30 },
  { "ERPCMISMATCH", 73 },
  { "ESHUTDOWN", 58 },
  { "ESOCKTNOSUPPORT", 44 },
  { "ESPIPE", 29 },
  { "ESRCH", 3 },
  { "ESTALE", 70 },
  { "ETIMEDOUT", 60 },
  { "ETOOMANYREFS", 59 },
  { "ETXTBSY", 26 },
  { "EUSERS", 68 },
  { "EXDEV", 18 },
};
const ProtobufCEnumDescriptor errors__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Errors",
  "Errors",
  "Errors",
  "",
  95,
  errors__enum_values_by_number,
  95,
  errors__enum_values_by_name,
  1,
  errors__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
