/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Sep 29 20:47:24 2018. */

#include "mirabuiltin.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t UtilsDumpHddKeysRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t UtilsDumpHddKeysResponse_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, UtilsDumpHddKeysResponse, error, error, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, UtilsDumpHddKeysResponse, encrypted, error, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, CALLBACK, OTHER, UtilsDumpHddKeysResponse, key, encrypted, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
