/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sun Sep 30 11:48:00 2018. */

#include "mirabuiltin.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MessageHeader_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MessageHeader, category, category, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MessageHeader, type, category, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MessageHeader, error, type, 0),
    PB_LAST_FIELD
};

const pb_field_t GetHddKeysRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, GetHddKeysRequest, header, header, &MessageHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t GetHddKeysResponse_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, GetHddKeysResponse, header, header, &MessageHeader_fields),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, GetHddKeysResponse, encrypted, header, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, GetHddKeysResponse, key, encrypted, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GetHddKeysRequest, header) < 65536 && pb_membersize(GetHddKeysResponse, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MessageHeader_GetHddKeysRequest_GetHddKeysResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(GetHddKeysRequest, header) < 256 && pb_membersize(GetHddKeysResponse, header) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MessageHeader_GetHddKeysRequest_GetHddKeysResponse)
#endif


/* @@protoc_insertion_point(eof) */
