/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Tue Oct 23 12:18:24 2018. */

#include "fileexplorer.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DirEnt_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DirEnt, fileno, fileno, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, DirEnt, reclen, fileno, 0),
    PB_FIELD(  3, UENUM   , REQUIRED, STATIC  , OTHER, DirEnt, type, reclen, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, DirEnt, name, type, 0),
    PB_LAST_FIELD
};

const pb_field_t OpenRequest_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, OpenRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, OpenRequest, path, header, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, OpenRequest, flags, path, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, OpenRequest, mode, flags, 0),
    PB_LAST_FIELD
};

const pb_field_t OpenResponse_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, OpenResponse, header, header, &MessageHeader_fields),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, OpenResponse, handle, header, 0),
    PB_LAST_FIELD
};

const pb_field_t CloseRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, CloseRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, CloseRequest, handle, header, 0),
    PB_LAST_FIELD
};

const pb_field_t CloseResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, CloseResponse, header, header, &MessageHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t ReadRequest_fields[5] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, ReadRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ReadRequest, handle, header, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, ReadRequest, offset, handle, 0),
    PB_FIELD(  4, UINT64  , REQUIRED, STATIC  , OTHER, ReadRequest, size, offset, 0),
    PB_LAST_FIELD
};

const pb_field_t ReadResponse_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, ReadResponse, header, header, &MessageHeader_fields),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, ReadResponse, data, header, 0),
    PB_LAST_FIELD
};

const pb_field_t ReadFileRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, ReadFileRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ReadFileRequest, path, header, 0),
    PB_LAST_FIELD
};

const pb_field_t ReadFileResponse_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, ReadFileResponse, header, header, &MessageHeader_fields),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, ReadFileResponse, offset, header, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, ReadFileResponse, data, offset, 0),
    PB_LAST_FIELD
};

const pb_field_t MakeDirectoryRequest_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, MakeDirectoryRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, MakeDirectoryRequest, path, header, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, MakeDirectoryRequest, mode, path, 0),
    PB_LAST_FIELD
};

const pb_field_t MakeDirectoryResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, MakeDirectoryResponse, header, header, &MessageHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t RemoveDirectoryRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, RemoveDirectoryRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, RemoveDirectoryRequest, path, header, 0),
    PB_LAST_FIELD
};

const pb_field_t RemoveDirectoryResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, RemoveDirectoryResponse, header, header, &MessageHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t UnlinkRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, UnlinkRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, UnlinkRequest, path, header, 0),
    PB_LAST_FIELD
};

const pb_field_t UnlinkResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, UnlinkResponse, header, header, &MessageHeader_fields),
    PB_LAST_FIELD
};

const pb_field_t TimeSpec_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, TimeSpec, sec, sec, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, TimeSpec, nsec, sec, 0),
    PB_LAST_FIELD
};

const pb_field_t StatRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, StatRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, StatRequest, path, header, 0),
    PB_LAST_FIELD
};

const pb_field_t StatResponse_fields[20] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, StatResponse, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, StatResponse, path, header, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, dev, path, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, ino, dev, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, mode, ino, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, nlink, mode, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, uid, nlink, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, gid, uid, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, rdev, gid, 0),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, StatResponse, atim, rdev, &TimeSpec_fields),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, StatResponse, mtim, atim, &TimeSpec_fields),
    PB_FIELD( 12, MESSAGE , OPTIONAL, STATIC  , OTHER, StatResponse, ctim, mtim, &TimeSpec_fields),
    PB_FIELD( 13, INT64   , OPTIONAL, STATIC  , OTHER, StatResponse, size, ctim, 0),
    PB_FIELD( 14, INT64   , OPTIONAL, STATIC  , OTHER, StatResponse, blocks, size, 0),
    PB_FIELD( 15, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, blksize, blocks, 0),
    PB_FIELD( 16, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, flags, blksize, 0),
    PB_FIELD( 17, UINT32  , OPTIONAL, STATIC  , OTHER, StatResponse, gen, flags, 0),
    PB_FIELD( 18, INT32   , OPTIONAL, STATIC  , OTHER, StatResponse, lspare, gen, 0),
    PB_FIELD( 19, MESSAGE , OPTIONAL, STATIC  , OTHER, StatResponse, birthtim, lspare, &TimeSpec_fields),
    PB_LAST_FIELD
};

const pb_field_t GetDentsRequest_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, GetDentsRequest, header, header, &MessageHeader_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, GetDentsRequest, path, header, 0),
    PB_LAST_FIELD
};

const pb_field_t GetDentsResponse_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, GetDentsResponse, header, header, &MessageHeader_fields),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, GetDentsResponse, entriesLeft, header, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, GetDentsResponse, entries, entriesLeft, &DirEnt_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(OpenRequest, header) < 65536 && pb_membersize(OpenResponse, header) < 65536 && pb_membersize(CloseRequest, header) < 65536 && pb_membersize(CloseResponse, header) < 65536 && pb_membersize(ReadRequest, header) < 65536 && pb_membersize(ReadResponse, header) < 65536 && pb_membersize(ReadResponse, data) < 65536 && pb_membersize(ReadFileRequest, header) < 65536 && pb_membersize(ReadFileResponse, header) < 65536 && pb_membersize(ReadFileResponse, data) < 65536 && pb_membersize(MakeDirectoryRequest, header) < 65536 && pb_membersize(MakeDirectoryResponse, header) < 65536 && pb_membersize(RemoveDirectoryRequest, header) < 65536 && pb_membersize(RemoveDirectoryResponse, header) < 65536 && pb_membersize(UnlinkRequest, header) < 65536 && pb_membersize(UnlinkResponse, header) < 65536 && pb_membersize(StatRequest, header) < 65536 && pb_membersize(StatResponse, header) < 65536 && pb_membersize(StatResponse, atim) < 65536 && pb_membersize(StatResponse, mtim) < 65536 && pb_membersize(StatResponse, ctim) < 65536 && pb_membersize(StatResponse, birthtim) < 65536 && pb_membersize(GetDentsRequest, header) < 65536 && pb_membersize(GetDentsResponse, header) < 65536 && pb_membersize(GetDentsResponse, entries[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_DirEnt_OpenRequest_OpenResponse_CloseRequest_CloseResponse_ReadRequest_ReadResponse_ReadFileRequest_ReadFileResponse_MakeDirectoryRequest_MakeDirectoryResponse_RemoveDirectoryRequest_RemoveDirectoryResponse_UnlinkRequest_UnlinkResponse_TimeSpec_StatRequest_StatResponse_GetDentsRequest_GetDentsResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ReadFileResponse.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
