
/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fileexplorer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "fileexplorer.pb-c.h"
void   dir_ent__init
                     (DirEnt         *message)
{
  static const DirEnt init_value = DIR_ENT__INIT;
  *message = init_value;
}
size_t dir_ent__get_packed_size
                     (const DirEnt *message)
{
  assert(message->base.descriptor == &dir_ent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dir_ent__pack
                     (const DirEnt *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dir_ent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dir_ent__pack_to_buffer
                     (const DirEnt *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dir_ent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DirEnt *
       dir_ent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DirEnt *)
     protobuf_c_message_unpack (&dir_ent__descriptor,
                                allocator, len, data);
}
void   dir_ent__free_unpacked
                     (DirEnt *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dir_ent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   echo_request__init
                     (EchoRequest         *message)
{
  static const EchoRequest init_value = ECHO_REQUEST__INIT;
  *message = init_value;
}
size_t echo_request__get_packed_size
                     (const EchoRequest *message)
{
  assert(message->base.descriptor == &echo_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t echo_request__pack
                     (const EchoRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &echo_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t echo_request__pack_to_buffer
                     (const EchoRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &echo_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EchoRequest *
       echo_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EchoRequest *)
     protobuf_c_message_unpack (&echo_request__descriptor,
                                allocator, len, data);
}
void   echo_request__free_unpacked
                     (EchoRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &echo_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   echo_response__init
                     (EchoResponse         *message)
{
  static const EchoResponse init_value = ECHO_RESPONSE__INIT;
  *message = init_value;
}
size_t echo_response__get_packed_size
                     (const EchoResponse *message)
{
  assert(message->base.descriptor == &echo_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t echo_response__pack
                     (const EchoResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &echo_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t echo_response__pack_to_buffer
                     (const EchoResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &echo_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EchoResponse *
       echo_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EchoResponse *)
     protobuf_c_message_unpack (&echo_response__descriptor,
                                allocator, len, data);
}
void   echo_response__free_unpacked
                     (EchoResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &echo_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_request__init
                     (OpenRequest         *message)
{
  static const OpenRequest init_value = OPEN_REQUEST__INIT;
  *message = init_value;
}
size_t open_request__get_packed_size
                     (const OpenRequest *message)
{
  assert(message->base.descriptor == &open_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_request__pack
                     (const OpenRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_request__pack_to_buffer
                     (const OpenRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenRequest *
       open_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenRequest *)
     protobuf_c_message_unpack (&open_request__descriptor,
                                allocator, len, data);
}
void   open_request__free_unpacked
                     (OpenRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   open_response__init
                     (OpenResponse         *message)
{
  static const OpenResponse init_value = OPEN_RESPONSE__INIT;
  *message = init_value;
}
size_t open_response__get_packed_size
                     (const OpenResponse *message)
{
  assert(message->base.descriptor == &open_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t open_response__pack
                     (const OpenResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &open_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t open_response__pack_to_buffer
                     (const OpenResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &open_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpenResponse *
       open_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpenResponse *)
     protobuf_c_message_unpack (&open_response__descriptor,
                                allocator, len, data);
}
void   open_response__free_unpacked
                     (OpenResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &open_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   close_request__init
                     (CloseRequest         *message)
{
  static const CloseRequest init_value = CLOSE_REQUEST__INIT;
  *message = init_value;
}
size_t close_request__get_packed_size
                     (const CloseRequest *message)
{
  assert(message->base.descriptor == &close_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t close_request__pack
                     (const CloseRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &close_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t close_request__pack_to_buffer
                     (const CloseRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &close_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CloseRequest *
       close_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CloseRequest *)
     protobuf_c_message_unpack (&close_request__descriptor,
                                allocator, len, data);
}
void   close_request__free_unpacked
                     (CloseRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &close_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   close_response__init
                     (CloseResponse         *message)
{
  static const CloseResponse init_value = CLOSE_RESPONSE__INIT;
  *message = init_value;
}
size_t close_response__get_packed_size
                     (const CloseResponse *message)
{
  assert(message->base.descriptor == &close_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t close_response__pack
                     (const CloseResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &close_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t close_response__pack_to_buffer
                     (const CloseResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &close_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CloseResponse *
       close_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CloseResponse *)
     protobuf_c_message_unpack (&close_response__descriptor,
                                allocator, len, data);
}
void   close_response__free_unpacked
                     (CloseResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &close_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_request__init
                     (ReadRequest         *message)
{
  static const ReadRequest init_value = READ_REQUEST__INIT;
  *message = init_value;
}
size_t read_request__get_packed_size
                     (const ReadRequest *message)
{
  assert(message->base.descriptor == &read_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_request__pack
                     (const ReadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &read_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_request__pack_to_buffer
                     (const ReadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &read_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadRequest *
       read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadRequest *)
     protobuf_c_message_unpack (&read_request__descriptor,
                                allocator, len, data);
}
void   read_request__free_unpacked
                     (ReadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &read_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   read_response__init
                     (ReadResponse         *message)
{
  static const ReadResponse init_value = READ_RESPONSE__INIT;
  *message = init_value;
}
size_t read_response__get_packed_size
                     (const ReadResponse *message)
{
  assert(message->base.descriptor == &read_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t read_response__pack
                     (const ReadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &read_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t read_response__pack_to_buffer
                     (const ReadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &read_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReadResponse *
       read_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReadResponse *)
     protobuf_c_message_unpack (&read_response__descriptor,
                                allocator, len, data);
}
void   read_response__free_unpacked
                     (ReadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &read_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_request__init
                     (WriteRequest         *message)
{
  static const WriteRequest init_value = WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t write_request__get_packed_size
                     (const WriteRequest *message)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_request__pack
                     (const WriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_request__pack_to_buffer
                     (const WriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteRequest *
       write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteRequest *)
     protobuf_c_message_unpack (&write_request__descriptor,
                                allocator, len, data);
}
void   write_request__free_unpacked
                     (WriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   write_response__init
                     (WriteResponse         *message)
{
  static const WriteResponse init_value = WRITE_RESPONSE__INIT;
  *message = init_value;
}
size_t write_response__get_packed_size
                     (const WriteResponse *message)
{
  assert(message->base.descriptor == &write_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t write_response__pack
                     (const WriteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &write_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t write_response__pack_to_buffer
                     (const WriteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &write_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WriteResponse *
       write_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WriteResponse *)
     protobuf_c_message_unpack (&write_response__descriptor,
                                allocator, len, data);
}
void   write_response__free_unpacked
                     (WriteResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &write_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   make_directory_request__init
                     (MakeDirectoryRequest         *message)
{
  static const MakeDirectoryRequest init_value = MAKE_DIRECTORY_REQUEST__INIT;
  *message = init_value;
}
size_t make_directory_request__get_packed_size
                     (const MakeDirectoryRequest *message)
{
  assert(message->base.descriptor == &make_directory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t make_directory_request__pack
                     (const MakeDirectoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &make_directory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t make_directory_request__pack_to_buffer
                     (const MakeDirectoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &make_directory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MakeDirectoryRequest *
       make_directory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MakeDirectoryRequest *)
     protobuf_c_message_unpack (&make_directory_request__descriptor,
                                allocator, len, data);
}
void   make_directory_request__free_unpacked
                     (MakeDirectoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &make_directory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   make_directory_response__init
                     (MakeDirectoryResponse         *message)
{
  static const MakeDirectoryResponse init_value = MAKE_DIRECTORY_RESPONSE__INIT;
  *message = init_value;
}
size_t make_directory_response__get_packed_size
                     (const MakeDirectoryResponse *message)
{
  assert(message->base.descriptor == &make_directory_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t make_directory_response__pack
                     (const MakeDirectoryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &make_directory_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t make_directory_response__pack_to_buffer
                     (const MakeDirectoryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &make_directory_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MakeDirectoryResponse *
       make_directory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MakeDirectoryResponse *)
     protobuf_c_message_unpack (&make_directory_response__descriptor,
                                allocator, len, data);
}
void   make_directory_response__free_unpacked
                     (MakeDirectoryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &make_directory_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   remove_directory_request__init
                     (RemoveDirectoryRequest         *message)
{
  static const RemoveDirectoryRequest init_value = REMOVE_DIRECTORY_REQUEST__INIT;
  *message = init_value;
}
size_t remove_directory_request__get_packed_size
                     (const RemoveDirectoryRequest *message)
{
  assert(message->base.descriptor == &remove_directory_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remove_directory_request__pack
                     (const RemoveDirectoryRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remove_directory_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remove_directory_request__pack_to_buffer
                     (const RemoveDirectoryRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remove_directory_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RemoveDirectoryRequest *
       remove_directory_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RemoveDirectoryRequest *)
     protobuf_c_message_unpack (&remove_directory_request__descriptor,
                                allocator, len, data);
}
void   remove_directory_request__free_unpacked
                     (RemoveDirectoryRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remove_directory_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   remove_directory_response__init
                     (RemoveDirectoryResponse         *message)
{
  static const RemoveDirectoryResponse init_value = REMOVE_DIRECTORY_RESPONSE__INIT;
  *message = init_value;
}
size_t remove_directory_response__get_packed_size
                     (const RemoveDirectoryResponse *message)
{
  assert(message->base.descriptor == &remove_directory_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remove_directory_response__pack
                     (const RemoveDirectoryResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remove_directory_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remove_directory_response__pack_to_buffer
                     (const RemoveDirectoryResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remove_directory_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RemoveDirectoryResponse *
       remove_directory_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RemoveDirectoryResponse *)
     protobuf_c_message_unpack (&remove_directory_response__descriptor,
                                allocator, len, data);
}
void   remove_directory_response__free_unpacked
                     (RemoveDirectoryResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remove_directory_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unlink_request__init
                     (UnlinkRequest         *message)
{
  static const UnlinkRequest init_value = UNLINK_REQUEST__INIT;
  *message = init_value;
}
size_t unlink_request__get_packed_size
                     (const UnlinkRequest *message)
{
  assert(message->base.descriptor == &unlink_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unlink_request__pack
                     (const UnlinkRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unlink_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unlink_request__pack_to_buffer
                     (const UnlinkRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unlink_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UnlinkRequest *
       unlink_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UnlinkRequest *)
     protobuf_c_message_unpack (&unlink_request__descriptor,
                                allocator, len, data);
}
void   unlink_request__free_unpacked
                     (UnlinkRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unlink_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unlink_response__init
                     (UnlinkResponse         *message)
{
  static const UnlinkResponse init_value = UNLINK_RESPONSE__INIT;
  *message = init_value;
}
size_t unlink_response__get_packed_size
                     (const UnlinkResponse *message)
{
  assert(message->base.descriptor == &unlink_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unlink_response__pack
                     (const UnlinkResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &unlink_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unlink_response__pack_to_buffer
                     (const UnlinkResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &unlink_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UnlinkResponse *
       unlink_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UnlinkResponse *)
     protobuf_c_message_unpack (&unlink_response__descriptor,
                                allocator, len, data);
}
void   unlink_response__free_unpacked
                     (UnlinkResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &unlink_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_spec__init
                     (TimeSpec         *message)
{
  static const TimeSpec init_value = TIME_SPEC__INIT;
  *message = init_value;
}
size_t time_spec__get_packed_size
                     (const TimeSpec *message)
{
  assert(message->base.descriptor == &time_spec__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_spec__pack
                     (const TimeSpec *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_spec__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_spec__pack_to_buffer
                     (const TimeSpec *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_spec__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeSpec *
       time_spec__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeSpec *)
     protobuf_c_message_unpack (&time_spec__descriptor,
                                allocator, len, data);
}
void   time_spec__free_unpacked
                     (TimeSpec *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_spec__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stat_request__init
                     (StatRequest         *message)
{
  static const StatRequest init_value = STAT_REQUEST__INIT;
  *message = init_value;
}
size_t stat_request__get_packed_size
                     (const StatRequest *message)
{
  assert(message->base.descriptor == &stat_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stat_request__pack
                     (const StatRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stat_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stat_request__pack_to_buffer
                     (const StatRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stat_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatRequest *
       stat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatRequest *)
     protobuf_c_message_unpack (&stat_request__descriptor,
                                allocator, len, data);
}
void   stat_request__free_unpacked
                     (StatRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stat_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stat_response__init
                     (StatResponse         *message)
{
  static const StatResponse init_value = STAT_RESPONSE__INIT;
  *message = init_value;
}
size_t stat_response__get_packed_size
                     (const StatResponse *message)
{
  assert(message->base.descriptor == &stat_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stat_response__pack
                     (const StatResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stat_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stat_response__pack_to_buffer
                     (const StatResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stat_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatResponse *
       stat_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatResponse *)
     protobuf_c_message_unpack (&stat_response__descriptor,
                                allocator, len, data);
}
void   stat_response__free_unpacked
                     (StatResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stat_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_dents_request__init
                     (GetDentsRequest         *message)
{
  static const GetDentsRequest init_value = GET_DENTS_REQUEST__INIT;
  *message = init_value;
}
size_t get_dents_request__get_packed_size
                     (const GetDentsRequest *message)
{
  assert(message->base.descriptor == &get_dents_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_dents_request__pack
                     (const GetDentsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_dents_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_dents_request__pack_to_buffer
                     (const GetDentsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_dents_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetDentsRequest *
       get_dents_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetDentsRequest *)
     protobuf_c_message_unpack (&get_dents_request__descriptor,
                                allocator, len, data);
}
void   get_dents_request__free_unpacked
                     (GetDentsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_dents_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   get_dents_response__init
                     (GetDentsResponse         *message)
{
  static const GetDentsResponse init_value = GET_DENTS_RESPONSE__INIT;
  *message = init_value;
}
size_t get_dents_response__get_packed_size
                     (const GetDentsResponse *message)
{
  assert(message->base.descriptor == &get_dents_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t get_dents_response__pack
                     (const GetDentsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &get_dents_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t get_dents_response__pack_to_buffer
                     (const GetDentsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &get_dents_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GetDentsResponse *
       get_dents_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GetDentsResponse *)
     protobuf_c_message_unpack (&get_dents_response__descriptor,
                                allocator, len, data);
}
void   get_dents_response__free_unpacked
                     (GetDentsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &get_dents_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue dir_ent__directory_type__enum_values_by_number[9] =
{
  { "DT_UNKNOWN", "DIR_ENT__DIRECTORY_TYPE__DT_UNKNOWN", 0 },
  { "DT_FIFO", "DIR_ENT__DIRECTORY_TYPE__DT_FIFO", 1 },
  { "DT_CHR", "DIR_ENT__DIRECTORY_TYPE__DT_CHR", 2 },
  { "DT_DIR", "DIR_ENT__DIRECTORY_TYPE__DT_DIR", 4 },
  { "DT_BLK", "DIR_ENT__DIRECTORY_TYPE__DT_BLK", 6 },
  { "DT_REG", "DIR_ENT__DIRECTORY_TYPE__DT_REG", 8 },
  { "DT_LNK", "DIR_ENT__DIRECTORY_TYPE__DT_LNK", 10 },
  { "DT_SOCK", "DIR_ENT__DIRECTORY_TYPE__DT_SOCK", 12 },
  { "DT_WHT", "DIR_ENT__DIRECTORY_TYPE__DT_WHT", 14 },
};
static const ProtobufCIntRange dir_ent__directory_type__value_ranges[] = {
{0, 0},{4, 3},{6, 4},{8, 5},{10, 6},{12, 7},{14, 8},{0, 9}
};
static const ProtobufCEnumValueIndex dir_ent__directory_type__enum_values_by_name[9] =
{
  { "DT_BLK", 4 },
  { "DT_CHR", 2 },
  { "DT_DIR", 3 },
  { "DT_FIFO", 1 },
  { "DT_LNK", 6 },
  { "DT_REG", 5 },
  { "DT_SOCK", 7 },
  { "DT_UNKNOWN", 0 },
  { "DT_WHT", 8 },
};
const ProtobufCEnumDescriptor dir_ent__directory_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DirEnt.DirectoryType",
  "DirectoryType",
  "DirEnt__DirectoryType",
  "",
  9,
  dir_ent__directory_type__enum_values_by_number,
  9,
  dir_ent__directory_type__enum_values_by_name,
  7,
  dir_ent__directory_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dir_ent__field_descriptors[4] =
{
  {
    "fileno",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DirEnt, fileno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reclen",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DirEnt, reclen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DirEnt, type),
    &dir_ent__directory_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DirEnt, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dir_ent__field_indices_by_name[] = {
  0,   /* field[0] = fileno */
  3,   /* field[3] = name */
  1,   /* field[1] = reclen */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange dir_ent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dir_ent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DirEnt",
  "DirEnt",
  "DirEnt",
  "",
  sizeof(DirEnt),
  4,
  dir_ent__field_descriptors,
  dir_ent__field_indices_by_name,
  1,  dir_ent__number_ranges,
  (ProtobufCMessageInit) dir_ent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor echo_request__field_descriptors[1] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EchoRequest, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned echo_request__field_indices_by_name[] = {
  0,   /* field[0] = message */
};
static const ProtobufCIntRange echo_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor echo_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EchoRequest",
  "EchoRequest",
  "EchoRequest",
  "",
  sizeof(EchoRequest),
  1,
  echo_request__field_descriptors,
  echo_request__field_indices_by_name,
  1,  echo_request__number_ranges,
  (ProtobufCMessageInit) echo_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor echo_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EchoResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned echo_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange echo_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor echo_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EchoResponse",
  "EchoResponse",
  "EchoResponse",
  "",
  sizeof(EchoResponse),
  1,
  echo_response__field_descriptors,
  echo_response__field_indices_by_name,
  1,  echo_response__number_ranges,
  (ProtobufCMessageInit) echo_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_request__field_descriptors[3] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OpenRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenRequest, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenRequest, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_request__field_indices_by_name[] = {
  1,   /* field[1] = flags */
  2,   /* field[2] = mode */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange open_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor open_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenRequest",
  "OpenRequest",
  "OpenRequest",
  "",
  sizeof(OpenRequest),
  3,
  open_request__field_descriptors,
  open_request__field_indices_by_name,
  1,  open_request__number_ranges,
  (ProtobufCMessageInit) open_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor open_response__field_descriptors[2] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "handle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(OpenResponse, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned open_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
  1,   /* field[1] = handle */
};
static const ProtobufCIntRange open_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor open_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpenResponse",
  "OpenResponse",
  "OpenResponse",
  "",
  sizeof(OpenResponse),
  2,
  open_response__field_descriptors,
  open_response__field_indices_by_name,
  1,  open_response__number_ranges,
  (ProtobufCMessageInit) open_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor close_request__field_descriptors[1] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CloseRequest, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned close_request__field_indices_by_name[] = {
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange close_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor close_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CloseRequest",
  "CloseRequest",
  "CloseRequest",
  "",
  sizeof(CloseRequest),
  1,
  close_request__field_descriptors,
  close_request__field_indices_by_name,
  1,  close_request__number_ranges,
  (ProtobufCMessageInit) close_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor close_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CloseResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned close_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange close_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor close_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CloseResponse",
  "CloseResponse",
  "CloseResponse",
  "",
  sizeof(CloseResponse),
  1,
  close_response__field_descriptors,
  close_response__field_indices_by_name,
  1,  close_response__number_ranges,
  (ProtobufCMessageInit) close_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_request__field_descriptors[3] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ReadRequest, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_request__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = offset */
  2,   /* field[2] = size */
};
static const ProtobufCIntRange read_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor read_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReadRequest",
  "ReadRequest",
  "ReadRequest",
  "",
  sizeof(ReadRequest),
  3,
  read_request__field_descriptors,
  read_request__field_indices_by_name,
  1,  read_request__number_ranges,
  (ProtobufCMessageInit) read_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor read_response__field_descriptors[2] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ReadResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ReadResponse, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned read_response__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = error */
};
static const ProtobufCIntRange read_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor read_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReadResponse",
  "ReadResponse",
  "ReadResponse",
  "",
  sizeof(ReadResponse),
  2,
  read_response__field_descriptors,
  read_response__field_indices_by_name,
  1,  read_response__number_ranges,
  (ProtobufCMessageInit) read_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_request__field_descriptors[3] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(WriteRequest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_request__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = handle */
  1,   /* field[1] = offset */
};
static const ProtobufCIntRange write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteRequest",
  "WriteRequest",
  "WriteRequest",
  "",
  sizeof(WriteRequest),
  3,
  write_request__field_descriptors,
  write_request__field_indices_by_name,
  1,  write_request__number_ranges,
  (ProtobufCMessageInit) write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor write_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WriteResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned write_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange write_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor write_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WriteResponse",
  "WriteResponse",
  "WriteResponse",
  "",
  sizeof(WriteResponse),
  1,
  write_response__field_descriptors,
  write_response__field_indices_by_name,
  1,  write_response__number_ranges,
  (ProtobufCMessageInit) write_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor make_directory_request__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MakeDirectoryRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MakeDirectoryRequest, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned make_directory_request__field_indices_by_name[] = {
  1,   /* field[1] = mode */
  0,   /* field[0] = path */
};
static const ProtobufCIntRange make_directory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor make_directory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MakeDirectoryRequest",
  "MakeDirectoryRequest",
  "MakeDirectoryRequest",
  "",
  sizeof(MakeDirectoryRequest),
  2,
  make_directory_request__field_descriptors,
  make_directory_request__field_indices_by_name,
  1,  make_directory_request__number_ranges,
  (ProtobufCMessageInit) make_directory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor make_directory_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MakeDirectoryResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned make_directory_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange make_directory_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor make_directory_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MakeDirectoryResponse",
  "MakeDirectoryResponse",
  "MakeDirectoryResponse",
  "",
  sizeof(MakeDirectoryResponse),
  1,
  make_directory_response__field_descriptors,
  make_directory_response__field_indices_by_name,
  1,  make_directory_response__number_ranges,
  (ProtobufCMessageInit) make_directory_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor remove_directory_request__field_descriptors[2] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RemoveDirectoryRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recursive",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RemoveDirectoryRequest, recursive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remove_directory_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
  1,   /* field[1] = recursive */
};
static const ProtobufCIntRange remove_directory_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor remove_directory_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RemoveDirectoryRequest",
  "RemoveDirectoryRequest",
  "RemoveDirectoryRequest",
  "",
  sizeof(RemoveDirectoryRequest),
  2,
  remove_directory_request__field_descriptors,
  remove_directory_request__field_indices_by_name,
  1,  remove_directory_request__number_ranges,
  (ProtobufCMessageInit) remove_directory_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor remove_directory_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RemoveDirectoryResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remove_directory_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange remove_directory_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor remove_directory_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RemoveDirectoryResponse",
  "RemoveDirectoryResponse",
  "RemoveDirectoryResponse",
  "",
  sizeof(RemoveDirectoryResponse),
  1,
  remove_directory_response__field_descriptors,
  remove_directory_response__field_indices_by_name,
  1,  remove_directory_response__number_ranges,
  (ProtobufCMessageInit) remove_directory_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unlink_request__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(UnlinkRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unlink_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange unlink_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unlink_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UnlinkRequest",
  "UnlinkRequest",
  "UnlinkRequest",
  "",
  sizeof(UnlinkRequest),
  1,
  unlink_request__field_descriptors,
  unlink_request__field_indices_by_name,
  1,  unlink_request__number_ranges,
  (ProtobufCMessageInit) unlink_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unlink_response__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UnlinkResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unlink_response__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange unlink_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unlink_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UnlinkResponse",
  "UnlinkResponse",
  "UnlinkResponse",
  "",
  sizeof(UnlinkResponse),
  1,
  unlink_response__field_descriptors,
  unlink_response__field_indices_by_name,
  1,  unlink_response__number_ranges,
  (ProtobufCMessageInit) unlink_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_spec__field_descriptors[2] =
{
  {
    "sec",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(TimeSpec, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nsec",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TimeSpec, nsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_spec__field_indices_by_name[] = {
  1,   /* field[1] = nsec */
  0,   /* field[0] = sec */
};
static const ProtobufCIntRange time_spec__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_spec__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeSpec",
  "TimeSpec",
  "TimeSpec",
  "",
  sizeof(TimeSpec),
  2,
  time_spec__field_descriptors,
  time_spec__field_indices_by_name,
  1,  time_spec__number_ranges,
  (ProtobufCMessageInit) time_spec__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stat_request__field_descriptors[2] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StatRequest, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stat_request__field_indices_by_name[] = {
  0,   /* field[0] = handle */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange stat_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stat_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatRequest",
  "StatRequest",
  "StatRequest",
  "",
  sizeof(StatRequest),
  2,
  stat_request__field_descriptors,
  stat_request__field_indices_by_name,
  1,  stat_request__number_ranges,
  (ProtobufCMessageInit) stat_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stat_response__field_descriptors[19] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StatResponse, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, dev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ino",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, ino),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nlink",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, nlink),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rdev",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, rdev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atim",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StatResponse, atim),
    &time_spec__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtim",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StatResponse, mtim),
    &time_spec__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ctim",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StatResponse, ctim),
    &time_spec__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StatResponse, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blocks",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StatResponse, blocks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blksize",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, blksize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gen",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, gen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lspare",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StatResponse, lspare),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "birthtim",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StatResponse, birthtim),
    &time_spec__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stat_response__field_indices_by_name[] = {
  9,   /* field[9] = atim */
  18,   /* field[18] = birthtim */
  14,   /* field[14] = blksize */
  13,   /* field[13] = blocks */
  11,   /* field[11] = ctim */
  2,   /* field[2] = dev */
  0,   /* field[0] = error */
  15,   /* field[15] = flags */
  16,   /* field[16] = gen */
  7,   /* field[7] = gid */
  3,   /* field[3] = ino */
  17,   /* field[17] = lspare */
  4,   /* field[4] = mode */
  10,   /* field[10] = mtim */
  5,   /* field[5] = nlink */
  1,   /* field[1] = path */
  8,   /* field[8] = rdev */
  12,   /* field[12] = size */
  6,   /* field[6] = uid */
};
static const ProtobufCIntRange stat_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor stat_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatResponse",
  "StatResponse",
  "StatResponse",
  "",
  sizeof(StatResponse),
  19,
  stat_response__field_descriptors,
  stat_response__field_indices_by_name,
  1,  stat_response__number_ranges,
  (ProtobufCMessageInit) stat_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_dents_request__field_descriptors[1] =
{
  {
    "path",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GetDentsRequest, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_dents_request__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange get_dents_request__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor get_dents_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetDentsRequest",
  "GetDentsRequest",
  "GetDentsRequest",
  "",
  sizeof(GetDentsRequest),
  1,
  get_dents_request__field_descriptors,
  get_dents_request__field_indices_by_name,
  1,  get_dents_request__number_ranges,
  (ProtobufCMessageInit) get_dents_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor get_dents_response__field_descriptors[3] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GetDentsResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entriesLeft",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GetDentsResponse, entriesleft),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GetDentsResponse, n_entries),
    offsetof(GetDentsResponse, entries),
    &dir_ent__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned get_dents_response__field_indices_by_name[] = {
  2,   /* field[2] = entries */
  1,   /* field[1] = entriesLeft */
  0,   /* field[0] = error */
};
static const ProtobufCIntRange get_dents_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor get_dents_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GetDentsResponse",
  "GetDentsResponse",
  "GetDentsResponse",
  "",
  sizeof(GetDentsResponse),
  3,
  get_dents_response__field_descriptors,
  get_dents_response__field_indices_by_name,
  1,  get_dents_response__number_ranges,
  (ProtobufCMessageInit) get_dents_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue file_transfer_commands__enum_values_by_number[11] =
{
  { "Echo", "FILE_TRANSFER_COMMANDS__Echo", 0 },
  { "Open", "FILE_TRANSFER_COMMANDS__Open", 1 },
  { "Close", "FILE_TRANSFER_COMMANDS__Close", 2 },
  { "GetDents", "FILE_TRANSFER_COMMANDS__GetDents", 3 },
  { "Read", "FILE_TRANSFER_COMMANDS__Read", 4 },
  { "Write", "FILE_TRANSFER_COMMANDS__Write", 5 },
  { "Unlink", "FILE_TRANSFER_COMMANDS__Unlink", 6 },
  { "Move", "FILE_TRANSFER_COMMANDS__Move", 7 },
  { "Stat", "FILE_TRANSFER_COMMANDS__Stat", 8 },
  { "MkDir", "FILE_TRANSFER_COMMANDS__MkDir", 9 },
  { "RmDir", "FILE_TRANSFER_COMMANDS__RmDir", 10 },
};
static const ProtobufCIntRange file_transfer_commands__value_ranges[] = {
{0, 0},{0, 11}
};
static const ProtobufCEnumValueIndex file_transfer_commands__enum_values_by_name[11] =
{
  { "Close", 2 },
  { "Echo", 0 },
  { "GetDents", 3 },
  { "MkDir", 9 },
  { "Move", 7 },
  { "Open", 1 },
  { "Read", 4 },
  { "RmDir", 10 },
  { "Stat", 8 },
  { "Unlink", 6 },
  { "Write", 5 },
};
const ProtobufCEnumDescriptor file_transfer_commands__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FileTransferCommands",
  "FileTransferCommands",
  "FileTransferCommands",
  "",
  11,
  file_transfer_commands__enum_values_by_number,
  11,
  file_transfer_commands__enum_values_by_name,
  1,
  file_transfer_commands__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
